Updates to TR-3 CT-16 & TR-5
finos/ai-readiness pull request #41
Opened 2024-09-12 15:34 UTC by aateeque

2024-09-13 10:14 UTC, ColinEberhardt commented
Thanks for another great contribution @aateeque 

For [TR-5: Instability in foundation model behaviour](https://github.com/aateeque/ai-readiness/blob/main/docs/_threats/tr-5.md) would it be possible to make it clearer that there are at least two sources of instability:
- Non-determinism - LLMs are probabilistic, which means given the same prompt, the output may differ between inferences.
- Versioning - This is where the underlying weights or architecture of the LLMs has changed. While this is more deterministic, some third-party hosted LLMs make these changes without notifying the end-user, which makes this a close relative to TR-11

2024-09-17 12:47 UTC, ColinEberhardt requested changes
as per in-line comment

2024-09-17 14:13 UTC, aateeque commented on docs/_threats/tr-5.md
> +Instability in foundation model behaviour would manifest itself as deviation in prompt output from previous tests.
Thanks for the great suggestion @ColinEberhardt; incorporarted

2024-09-17 14:16 UTC, aateeque commented
Thanks @ColinEberhardt - changes incorporated

2024-09-18 14:11 UTC, merged

2024-12-12 20:42 UTC, lucaborella89 commented
@aateeque @ColinEberhardt as per MS review (https://github.com/finos/ai-readiness/issues/79), TR5 could be merged with TR6